#!/usr/bin/env python3
"""Generate the new app.js with unified score from sono_score.py"""

import json, os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Read config JSON for reference
with open(os.path.join(SCRIPT_DIR, 'sono-score-config.json')) as f:
    cfg = json.load(f)

B = cfg['barreras']

# Build the JS file
# Using raw strings to avoid escaping hell
lines = []
def L(s):
    lines.append(s)

L('(function(){')
L('"use strict";')
L('')
L('var CTF="1m",CA="BTC";')
L('var ST={price:0,high:0,low:0,ch:0,kl:{},fg:50,vx:0,db:0,de:0,mc:0,er:1.08};')
L('var MA_CACHE={};')
L('var _dataReady=false;')
L('var SWR={fg:0,cg:0,vx:0,eur:0};')
L('var SWR_TTL={fg:300000,cg:180000,vx:120000,eur:900000};')
L('function swrOk(k){return SWR[k]&&Date.now()-SWR[k]<SWR_TTL[k];}')
L('var AS={BTC:"BTCUSDT",ETH:"ETHUSDT",SOL:"SOLUSDT",XRP:"XRPUSDT"};')
L('function $i(i){return document.getElementById(i)}')
L('function fk(n){return n>=1e12?"$"+(n/1e12).toFixed(2)+"T":n>=1e9?"$"+(n/1e9).toFixed(1)+"B":n>=1e6?"$"+(n/1e6).toFixed(0)+"M":"$"+n.toFixed(0)}')
L('function fm(n){return "$"+Math.round(n).toLocaleString("en-US")}')
L('')
L('// ===== SCORE MAESTRO UNIFICADO v2 =====')
L('// Alineado con sono_score.py (Python) — fuente canonica')
L('// Lee sono-score-config.json como unica fuente de verdad')
L('// =========================================')
L('')
L('var SCORE_CFG = null;')
L('')
L('function loadScoreConfig(){')
L('  return fetch("/sono-score-config.json",{cache:"no-store"})')
L('    .then(function(r){return r.json()})')
L('    .then(function(cfg){ SCORE_CFG = cfg; })')
L('    .catch(function(){')
L('      SCORE_CFG = ' + json.dumps(cfg, ensure_ascii=False) + ';')
L('    });')
L('}')
L('')
L('// SMA pura — mismo algoritmo que calc_ma Python')
L('function sm(a,p){')
L('  if(!a||a.length<p) return null;')
L('  var s=0;')
L('  for(var i=a.length-p;i<a.length;i++) s+=+a[i];')
L('  return s/p;')
L('}')
L('')
L('// RSI 14 — Cutler RSI, mismo que calc_rsi Python')
L('function rs(c,p){')
L('  p=p||14;')
L('  if(!c||c.length<p+1) return null;')
L('  var g=0,l=0;')
L('  for(var i=c.length-p;i<c.length;i++){')
L('    var d=+c[i]-+c[i-1];')
L('    if(d>0) g+=d; else l-=d;')
L('  }')
L('  if(l===0) return 100;')
L('  return Math.round(100 - 100 / (1 + (g/p) / ((l/p)||0.0001)));')
L('}')
L('')
L('// ADX 14 — mismo que calc_adx Python')
L('function ax(h,l,c,p){')
L('  p=p||14;')
L('  if(!c||c.length<p*2) return null;')
L('  var pD=[],mD=[],tr=[];')
L('  for(var i=1;i<c.length;i++){')
L('    var pH=+h[i]-+h[i-1],mL=+l[i-1]-+l[i];')
L('    pD.push(pH>mL&&pH>0?pH:0);')
L('    mD.push(mL>pH&&mL>0?mL:0);')
L('    tr.push(Math.max(+h[i]-+l[i],Math.abs(+h[i]-+c[i-1]),Math.abs(+l[i]-+c[i-1])));')
L('  }')
L('  var sp=0,sm2=0,st=0;')
L('  for(var i=pD.length-p;i<pD.length;i++){sp+=pD[i];sm2+=mD[i];st+=tr[i]}')
L('  st=st||1;')
L('  var pDI=Math.round(100*sp/st),mDI=Math.round(100*sm2/st);')
L('  if(pDI+mDI===0) return 0;')
L('  return Math.round(Math.abs(pDI-mDI)/((pDI+mDI)||1)*100);')
L('}')
L('')
L('// Bollinger %B — mismo que calc_bb Python')
L('function bb(c,p,k){')
L('  p=p||20;k=k||2;')
L('  if(!c||c.length<p) return{pb:null};')
L('  var sl=c.slice(-p),m=0;')
L('  for(var i=0;i<p;i++) m+=+sl[i];')
L('  m/=p;')
L('  var sd=0;')
L('  for(var i=0;i<p;i++) sd+=(+sl[i]-m)*(+sl[i]-m);')
L('  sd=Math.sqrt(sd/p);')
L('  var u=m+k*sd,d=m-k*sd;')
L('  if(u-d===0) return{pb:0.5};')
L('  return{pb:(+c[c.length-1]-d)/(u-d)};')
L('}')
L('')
L('// Hash rapido para MA_CACHE — basado en timestamp de ultima vela')
L('function hashArr(arr){')
L('  if(!arr||arr.length===0) return "";')
L('  var last=arr[arr.length-1];')
L('  return arr.length+"_"+(+last[0]||0);')
L('}')
L('')
L('// Score Maestro completo — ALINEADO con compute_score Python')
L('function cs(c){')
L('  if(!c||c.length<30) return null;')
L('  var cl=c.map(function(x){return+x[4]}),hi=c.map(function(x){return+x[2]}),lo=c.map(function(x){return+x[3]}),p=cl[cl.length-1];')
L('  var tLen=cl.length;')
L('  var k=CTF;')
L('  var h=hashArr(c);')
L('  // MA_CACHE con hash real — no compara arrays por referencia')
L('  var m6=null,m40=null,m70=null,m2=null;')
L('  var k6=k+"_6_"+h, k40=k+"_40_"+h, k70=k+"_70_"+h, k200=k+"_200_"+h;')
L('  if(MA_CACHE[k6]){m6=MA_CACHE[k6]}else if(tLen>=6){m6=sm(cl,6);MA_CACHE[k6]=m6}')
L('  if(MA_CACHE[k40]){m40=MA_CACHE[k40]}else if(tLen>=40){m40=sm(cl,40);MA_CACHE[k40]=m40}')
L('  if(MA_CACHE[k70]){m70=MA_CACHE[k70]}else if(tLen>=70){m70=sm(cl,70);MA_CACHE[k70]=m70}')
L('  if(tLen>=200){')
L('    if(MA_CACHE[k200]){m2=MA_CACHE[k200]}else{m2=sm(cl,200);MA_CACHE[k200]=m2}')
L('  }')
L('  // P1 — Tendencia (max 35) — ALINEADO con Python')
L('  var p1=0;')
L('  if(m6!==null&&m40!==null) p1+=m6>m40?12:0;')
L('  if(m6!==null&&m70!==null) p1+=m6>m70?10:0;')
L('  if(m40!==null&&m2!==null) p1+=m40>m2?13:0;')
L('  // P2 — Momentum (max 35) — ALINEADO con Python')
L('  var r=rs(cl),a=ax(hi,lo,cl),p2=0;')
L('  if(a!==null){')
L('    p2+=a>35?15:a>25?10:3;')
L('  }')
L('  if(r!==null){')
L('    p2+=r>=50&&r<70?12:r>=35?7:2;')
L('  }')
L('  if(m2!==null){')
L('    p2+=p>m2?8:0;')
L('  }')
L('  // P3 — Bollinger (max 30) — ALINEADO con Python')
L('  var bv=bb(cl).pb,p3=0;')
L('  if(bv!==null){')
L('    if(bv<0.15) p3=28;')
L('    else if(bv<0.35) p3=20;')
L('    else if(bv<0.65) p3=14;')
L('    else if(bv<0.85) p3=7;')
L('    else p3=2;')
L('  }')
L('  var total=Math.min(100,Math.round(p1+p2+p3));')
L('  return{sc:total,p1,p2,p3,m6,m40,m70,m2,p,r,a,pb:bv,tLen:tLen,ma200Avail:m2!==null};')
L('}')
L('')
L('// Classify score — ALINEADO con classify_score Python')
L('classify_js = """')
L('function sl(s){')
L('  var B = SCORE_CFG ? SCORE_CFG.barreras : null;')
L('  if(!B){')
L('    if(s>=%(cf)s) return["COMPRA FUERTE","pgg"];')
L('    if(s>=%(c)s) return["COMPRA","pgg"];')
L('    if(s>=%(a)s) return["ACUMULAR","pb"];')
L('    if(s>=%(n)s) return["NEUTRAL","pgg2"];')
L('    if(s>=%(d)s) return["VENTA","pw"];')
L('    if(s>=%(v)s) return["VENTA FUERTE","prr"];')
L('    return["CAPITULACION","prr"];')
L('  }')
L('  if(s>=B.compra_fuerte) return["COMPRA FUERTE","pgg"];')
L('  if(s>=B.compra) return["COMPRA","pgg"];')
L('  if(s>=B.acumulacion) return["ACUMULAR","pb"];')
L('  if(s>=B.neutral) return["NEUTRAL","pgg2"];')
L('  if(s>=B.distribucion) return["VENTA","pw"];')
L('  if(s>=B.venta) return["VENTA FUERTE","prr"];')
L('  return["CAPITULACION","prr"];')
L('}')
L('""" % {"cf": B["compra_fuerte"], "c": B["compra"], "a": B["acumulacion"], "n": B["neutral"], "d": B["distribucion"], "v": B["venta"]}')
L('')

# Actually that won't work in Python. Let me rethink.
# Just write the whole thing programmatically
# Reset
lines = []
# ... not efficient. Let me just write the whole JS as a single string.

# Read the original app.js, modify the score functions
with open(os.path.join(SCRIPT_DIR, 'frontend', 'app.js'), 'r', encoding='utf-8') as f:
    original = f.read()

print(f"Original: {len(original)} chars")
print("Done")
