name = "sono-bot"
main = "src/worker.js"
compatibility_date = "2026-06-01"

# KV para persistencia de estado
[[kv_namespaces]]
binding = "SONO_BOT_KV"
id = "faaaf6ada96544329ab9ea6f9340c2c4"
preview_id = "7df382b7958a45c99d73c725049f5981"

# Cron: cada 2 minutos
[triggers]
crons = ["*/2 * * * *"]
